// export {default as Note} from './Navbar';
export {default as Note}from './Note';
export {default as CartDrawer}  from './CartDrawer';
export {default as Footer}from './Footer';
export {default as BrowseCategories} from './BrowseCategories';
export {default as Signup}from './Signup';
export {default as Login} from './Login';
export {default as Products} from './Products';
export {default as HomepageComp} from './HomePageComp';
export {default as Navbar} from './Navbar';
