export {default as totoes} from './images/totes1.jpeg';
export {default as heroImage} from './images/vecteezy_ai-generated-clothes-hanging-on-a-rack-in-a-shop-close-up_35775430.jpg';
export {default as productImage1} from './images/1-removebg-preview.png';
export {default as productImage2} from './images/totes1.jpeg';
export {default as productImage3} from './images/totes1.jpeg';
export {default as brandImage} from './images/totes1.jpeg';
export {default as testimonialImage} from './images/totes1.jpeg';
export {default as newsletterImage} from './images/totes1.jpeg';
export {default as headband1} from './images/1-removebg-preview.png';
export {default as headband2} from './images/17_dd321fe4-c31e-4b74-9b98-548d4a601a0b-removebg-preview.png';
export {default as headband3} from './images/1b3bdffdc4775a3a77e9eede208fce0f-removebg-preview.png';
export {default as headband4} from './images/1eab3449cba6b50922760ed5b0880e19-removebg-preview (1).png';
export {default as headband5} from './images/41Un7m8HUPL._SS600_-removebg-preview.png';
export {default as headband6} from './images/5f2c7e640db8469af0230878660970b9-removebg-preview.png';
export {default as headband7} from './images/61IiR6ZypJL._AC_UF1000_1000_QL80_-removebg-preview.png';
export {default as headband8} from './images/71sX-3TCQXL._AC_UF1000_1000_QL80_-removebg-preview.png';
export {default as headband9} from './images/81sxMjGJ4PL._AC_UY1000_-removebg-preview.png';
// export {default as headband10} from './images/totes1.jpeg';
// export {default as productImage1} from './images/totes1.jpeg';
// export {default as productImage2} from './images/totes1.jpeg';
// export {default as productImage3} from './images/totes1.jpeg;
// export {default as brandImage} from './images/totes1.jpeg';